Received: from EMSTXS.Ontyme.Tymnet by X62.Tymnet; Tue, 20 Jan 87 11:41:34 PST
From: MDISF.TS@EMSTXS.Ontyme.Tymnet 
Date: 20 JAN 87 10:37:49 
To: TXS.D/COFFEY@EMSTXS.Ontyme.Tymnet 
Cc: TXS.D/COFFEY@Ontyme.Tymnet, IOD.CUPERTINO@Ontyme.Tymnet 
Message-id: R59688@Ontyme.Tymnet 
Subject: Replacement for PERP & PCOM. 

 
 
 
 
 
  -----------------------M E M O R A N D U M------------------------------
  MCDONNELL DOUGLAS                    Tel. [33](1)46.02.70.12
  INFORMATION SYSTEMS FRANCE
  Technical Services.                  Ontyme : MDISF.TS
  ------------------------------------------------------------------------
 
  Date:    January 20th, 1987 - 7:36 p.m. CST
 
  To:      Dennis Coffey (TXS.D/COFFEY)
 
  Copies:  Ken BeDell (IOD.CUPERTINO)
 
  From:    Peter Stratman (MDISF.TS)
 
  Subject: Replacement for PERP & PCOM.
  ------------------------------------------------------------------------
 
 
  Dennis,
 
  This is a copy of a memo I sent  you on Dec. 4th. I have not received an
  answer to this message yet. Did it get lost ?
 
 
  Copy of R24821 of 04-DEC-1986 :
 
  Now that the new job processor is operational on U.S. TYMCOM X's I would
  like  to  investigate the  possibility  of  upgrading our  machines  and
  installing the product  on our machines in Paris. Could  you please pro-
  vide me with  the list of operations  that will be necessary  to upgrade
  our 2020's to Monitor version P034/P with SUBMIT ?
 
  Thank you, and best regards, Peter.
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
                                    -1-
From: Joe Smith <JMS@X930> 
Date: Mon, 1 Jun 87 11:37:48 PDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: HELP version 6(75)-2 has been distributed to all systems. 

Sometime back we decided to have the HELP command run (SYS)HELP instead of
RPG.  I put a hack into DEC's HELP program so that it can find files on (SYS).
It now responds to "HELP" to give general info, "HELP *" to give a list of
available topics.  Once we have a suitable base of *.HLP files distributed,
we should mention it in (SYS)ACCESS.MSG.   /Joe
From: Carl A Baltrunas <Carl@X930.Tymnet> 
Date: Wed, 17 Jun 87 2:05:16 PDT 
To: Monitor Group <CARL@X930>, Osman Guven <Osman@X930.Tymnet>, Joe Smith
	<JMS@X930.Tymnet> 
Cc: Craig Fletcher <fletcherc@X930.Tymnet>, Dennis Coffey <dencoff@X930.Tymnet>
	
Subject: (INFO)AGENDA.TXT 

I made up an agenda... of course, it was written in a vacuum, so there
may be things I left out, and things I put in that should be thrown out.
Please feel free to look at the agenda and make changes.

I moved it to (INFO)AGENDA.TXT out of (MONDOC) as mentioned last week.
I also typed in the significant things I had noted from the last meeting
as the minutes.  The minutes currently precede the agenda, since they
inevitably replace the agenda.. if we follow it !!!

See you all at the meeting.
From: Carl A Baltrunas <Carl@X930.Tymnet> 
Date: Wed, 17 Jun 87 2:10:33 PDT 
To: Monitor Group <CARL@X930>, Osman Guven <Osman@X930.Tymnet>, Joe Smith
	<JMS@X930.Tymnet> 
Cc: Craig Fletcher <fletcherc@X930.Tymnet>, Dennis Coffey <dencoff@X930.Tymnet>
	
Subject: AGENDA - MINUTES 

Please read the first couple of pages in (INFO)AGENDA.TXT before the
meeting.  The minutes of the previous meeting(s) can be found herein
and should be read prior to the meeting so we do not waste valuable
meeting time rehashing last week's meeting.

/Carl
From: Joe Smith <JMS@X930> 
Date: Fri, 17 Jul 87 15:05:37 PDT 
To: dencoff 
Subject: DRAFT PROPOSAL CHARTER REWRITE 

(begin forwarded message)

Received: from F29.Tymnet by X930.Tymnet; Fri, 10 Jul 87 21:50:49 PDT
Received: from EMSFSC.Ontyme.Tymnet by F29.Tymnet; Fri, 10 Jul 87 21:44:16 PDT
Return-path: <FSC.E/HALL@EMSFSC.Ontyme.Tymnet> 
From: FSC.E/HALL@EMSFSC.Ontyme.Tymnet 
Date: 10 JUL 87 21:16:46 
To: FSC.JM/SMITH@EMSFSC.Ontyme.Tymnet 
Message-id: P16724@Ontyme.Tymnet 
Subject: DRAFT PROPOSAL CHARTER REWRITE 
Proposalforcharterupdate: 

To : Russ Rawlins 
From : Edmond Hall 
Copies : K. Gonzales 
             C. Fletcher 
             B. Wu 
	J. M. Smith 
Subject :  Proposal for charter update 


              CHARTER FOR THE  THIRD PARTY  PRODUCT SUPPORT  GROUP 


Provide to the field ; 
     	o	Documentation assistance 
	o	Simplified procedures for tasks as needed 
	o	Field handbooks 
	o	Support Plans for new products 
	o	ECO/FCO  database 
	o	Technical tips database 
	o	Diagnostic package (creation and distribution) 
	o	Telephone technical support 
	o	Limited on-site technical support 
	o	Local Area Network  support 
	o	Remote monitoring capability 
	o	Remote diagnostic capability 
	o	Technical seminars as need arises 
	o	Product seminars for managers 
	o	Configuration information 
	o	Other support as needs dictate 


Provide to tymnet group ; 
	o	Documentation assistance 
	o	ECO/FCO  information 
	o	Procedures 
	o	Other support as needs dictate 


Provide to training ; 
	o	Evaluation of course content 
	o	Recommendations for new courses or content 
	o	New product instruction 
	o	Other support as needs dictate 




Provide to logistics ; 
	o	Sparing level recommendations 
	o	Lists of special tools and test equipments 
	o	Other support as needs dictate 


Provide also ; 
	o	Product evaluations and MTBF data if available 
	o	Recommended spares lists 
	o	Safety bulletins as necessary 
	o	Other support as needs dictate 
	o	Provide any other procedures or recommendations which  
	 	can positively influence the proficiency and profitability 
		of our organization as a whole 




RETAIN THE SOFTWARE SUPPORT LIST AS IS 





TYPE LINE

(end forwarded message)

This is what they expect to go over at the July 23rd meeting.
From: Joe Smith <JMS@X930> 
Date: Tue, 28 Jul 87 9:47:01 PDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: We need to purge the PERP examples from the AFD document. 

(DNDUTIL:*)AUTOFD.DOC and (ISISDOC:*)AUTOFD.DOC describe the 10 or files
needed to run AFD.  It also has two examples on how to run PERP to start
AFD.  We need to rip out those examples and replace them with SUBMIT
commands.  See (JMS:930)AUTOFD.WHR for the locations of the files.  /Joe
From: Carl A Baltrunas <Carl@X930.Tymnet> 
Date: Mon, 3 Aug 87 22:04:42 PDT 
To: dencoff 
Subject: TYMNET call for (DIALNET) 

Dennis,
  I spoke with the person who called me, that Osman referred to you about
problems with SUBMIT and trying to setup something similar to what they had
with PERP and PCOM...

  Please get back with me before calling her back.  I think we can solve
most of her problems with the newest release of XEXEC.

/Carl
From: Joe Smith <JMS@X930> 
Date: Tue, 4 Aug 87 14:56:01 PDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: (M33)P035C.DOC has release notes for P035/C. 

The modification history (all the details of everything added since P035/P)
is in (M33)P035C.MEM, the release nodes (english translations) are in
(M33)P035C.DOC.  (M33)STOPCD.MEM has also been updated.  /Joe
From: Joe Smith <JMS@X930> 
Date: Tue, 4 Aug 87 17:18:23 PDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: Cause of SAXINY stopcodes. 

?INFO stopcode "SAXINY" at 02-Aug-1987 12:33:32   T4 = 400000,,421043
?INFO stopcode "SAXINY" at 02-Aug-1987 12:33:38   T4 = 400000,,421143

In the right half:
  400000 = Interrupt request from SA10
   20000 = SA10 channel 1 (disk) is enabled for interrupt
    1000 = The "GO" flag is set for SA10 channel 1 (disk)
     100 = Status available from channel 0 (tape)
      40 = Status available from channel 1 (disk)
       3 = SA10 is using PI channel 3

In the left half:
  400000 = Dummy bit set to indicate that one of bits 29-32 are set in RH
     000 = Octal unit device address (8 bits)

SAXINY means that one of the two disk controllers has told the SA10 to
interrupt the PDP-10, but the controller did not identify itself.  Controller
BPA (which is wired for 'C0' to 'CF') is supposed to report unit device
addresses in the range 300 to 317 and controller BPB (wired for 'D0' to 'DF')
is supposed to report unit device addresses in the range 320 to 337.  All the
SAXINY reports I have looked at show a unit device address of 000.  One of
the two controllers is returning bad status.

SAXINY occurs whenever the system gets an interrupt and cannot identify which
particular disk (or controller) was the cause of the interrupt.  THUNG occurs
when a disk transfer is started, but the "done" interrupt gets lost.  I would
expect each THUNG to be preceded by a SAXINY report.     /Joe
Received: from F29.Tymnet by X930.Tymnet; Mon, 27 Jul 87 11:44:30 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 27 Jul 87 11:34:31 PDT
From: TYMOPS.N/NILES@EMSTXS.Ontyme.Tymnet 
Date: 27 JUL 87 19:08:33 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: M08084@Ontyme.Tymnet 
Subject: Removal of Trash for MOve 
Resent-from: Tymcom-X Supervisor <TXSSUP@X930.Tymnet> 
Resent-date: Fri, 7 Aug 87 16:15:45 PDT 
ResentCarl A Baltrunas <carl@X930.Tymnet>, Osman Guven
	<osman@X930.Tymnet>, Joe Smith <jms@X930.Tymnet> 
Resent-cc: Craig Fletcher <fletcherc@X930.Tymnet>, DenCoff 

     TO:       All South Bay MDC Personnel

     FROM:     Dick Denesha

     DATE:     July 27, 1987

     SUBJECT:  Removal of Trash for MOve
     =================================================================

     TRASH, TRASH and more TRASH.  Here is how we are going to get rid
     of it!!.

     Carts marked with TRASH will be placed in each building at
     various locations.  They may be used by anyone, and Facilities
     Maintenance or the janitor will empty them as needed.  If you
     need immediate service, call 446-8048 for action.  PLEASE! do not
     put any WET trash into these carts.

     Now is a good time to get rid of outdated phone books and
     directories.  There will be a limited number of new San Jose
     books available for the Fremont movees, so everyone else please
     bring your 1987 books with you.

     The ELECTRICAL POWER STRIPS, EXTENSION CORDS, HEATERS AND FANS
     will not be needed or allowed (except in special circumstances)
     in the new buildings.  Please leave them on your desk for pickup
     by Facilities Maintenance.

     If you have any questions, please contact your local maintenance
     person:

     VALLEY GREEN        IGNACIO GUERRERO              446-6008

     BUBB RD.            BILL HUNT                     446-6040

     LIBERTY             YASUO KOTAKA                  415/794-2550

     OPW                 SLIM DAVENPORT                432-5224

     EMERGENCY FROM ANY LOCATION - 408-446-8048
From: Joe Smith <JMS@X930> 
Date: Sun, 9 Aug 87 15:28:54 PDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: 2nd draft of P035C.DOC is ready. 

Osman, Dennis,
  Please check (M33)P035C.DOC for omissions, misspellings, etc.  It
currently includes Carl's and Craig's comments.  /Joe
From: Dennis Coffey (Tymcom-X Systems) <DenCoff@X930> 
Date: Mon, 10 Aug 87 9:35:07 PDT 
To: tymis.j/wagner@ontyme 
Cc: Craig <FletcherC> 
Subject: Internal Order. 



                                  MEMORANDUM


                                                              TYMCOM-X SYSTEMS

DATE:  10-Aug-87    9:36:10

  TO:  Julie Wagner

  CC:  Craig Fletcher

FROM:  Dennis Coffey  (Tymcom-X Systems)

SUBJ:  Network connectivity needed at the new super-center.

------------------------------------------------------------------------------

Julie,

    McDonnell Douglas Field Service Company needs network connectivity at the
new Nicholson Lane Super-Center.  We need four Tymnet-II T-201 sync links.  We
will be installing TYMCOM-X "lab" hosts and their base nodes at the Nicholson
Lane site, in the node room with the engines.  
	
    The bases for these hosts run on our own hardware (DEC LSI-11s).  They
talk Tymnet-II T-201 protocol to the engines.  These hosts and bases are
currently connected to the public network here, at the Liberty Street, Fremont
office.

    The network node and host numbers for the LSI-11s currently are:  Node
6657 (host :4511) and node 6760 (host :3984).  (Their engine neighbors
currently are nodes 3143 and 3146.)  We request two public network links for
each of these nodes, and request that one of the two links on each of our
nodes be an X-Link, for flexibility.

    This will be charged against Department number:  90842.  This department
is MDFSCO Third Party Software Product Support.  The manager is Craig
Fletcher.

    If you have questions, please call me at (415) 794-2588, or tie-line 116
ext. 2588, or Ontyme me at TXS.D/COFFEY.
Received: from F29.Tymnet by X930.Tymnet; Wed, 12 Aug 87 14:44:22 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Wed, 12 Aug 87 14:41:03 PDT
Return-path: <NTD.D/HOPKINS@EMSTXS.Ontyme.Tymnet> 
From: NTD.D/HOPKINS@EMSTXS.Ontyme.Tymnet 
Date: 12 AUG 87 11:44:33 
To: TXS.D/COFFEY@EMSTXS.Ontyme.Tymnet 
Message-id: I70808@Ontyme.Tymnet 
Subject: Bubbnet spooling and printing 

Dennis,

I am sorry it took so long to get back to you, but Bubbnet has
been very busy moving to 1st street. My original question was
(to refresh you and Io of the situation) could Bubbnet get the
spool program modified so that Bubbnet users could enter spool
requests and get them printed at a remote site? My recolection
of the Ontyme you sent back to me was that you needed the
destination nodes of remote printing stations as well as the
originatiting nodes of the requests.
I have found that Bubbnet node 4166 has a printer interface card
that two fullcase impact printers could be connected.
The building consats that the requests will originate from are
nodes 4165,4044,4647,4357,4067,4055 and 4646. 

I hope this is enough information to get things started. I have
been assured that it will be no problem to modify the titym files
of these nodes once we know what to change. Should you need more information
or have instructions for us please respond by Ontyme (I am hard to
track down by phone) or if phone me at
922-6145. Thanks for your help 
                                  Sincerely
                                   Dave Hopkins
From: Dennis Coffey (Tymcom-X Systems) <DenCoff@X930> 
Date: Wed, 12 Aug 87 14:46:42 PDT 
To: NTD.D/HOPKINS@EMSTXS.Ontyme.Tymnet 
Subject: Re: Bubbnet spooling and printing 
In-reply-to: I70808@Ontyme.Tymnet of 12 AUG 87 11:44:33

Dave,

  I believe you have given me all the info I need to bring the SPOOL program's
data base up to date for BUBBNET.  

Thanks,
-D.-
From: Dennis Coffey (Tymcom-X Systems) <DenCoff@X930> 
Date: Wed, 12 Aug 87 16:14:50 PDT 
To: NTD.D/HOPKINS@Ontyme.Tymnet 
Subject: Re: Bubbnet spooling and printing 
In-reply-to: I70808@Ontyme.Tymnet of 12 AUG 87 11:44:33

Dave,

  Thank you for the info, re. the new SPOOL site.  It will be much better for
you guys to have your own SPOOL station on site.  To keep the BUBBNET SPOOL
program informative to users, we need the location (i.e.: address) and the
operator's telephone number for the SPOOL site.  

  Since this is the only SPOOL location on BUBBNET, I'm removing all
references to other sites from B39's SPOOL station data base.

  Please get me the info about the new SPOOL site, and please let me know when
it will become active, so I can install the data base files.

  Thanks,
-D.-
From: Joe Smith <JMS@X930> 
Date: Wed, 12 Aug 87 20:25:47 PDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: System DD is up as host 95. 

The 2020 with 3 RP06 disks is up an in the network as host 95.
SYSNO says X118 though, the real 95 (hardware CC) has an LP20 printer interface
on its UNIBUS but this system (118) does not.  That is the reason why hardware
DD cannot use 95's regular monitor.

Right now only the 1-tape save set has been restored.   /Joe
Received: from F29.Tymnet by X930.Tymnet; Tue, 11 Aug 87 14:34:03 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Tue, 11 Aug 87 14:25:02 PDT
From: TYMOPS.N/NILES@EMSTXS.Ontyme.Tymnet 
Date: 11 AUG 87 21:50:27 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: M11586@Ontyme.Tymnet 
Subject: FURNITURE TAGGING 
Resent-from: Tymcom-X Supervisor <TXSSUP@X930.Tymnet> 
Resent-date: Fri, 14 Aug 87 12:55:09 PDT 
Resent-to: Carl A Baltrunas <carl@X930.Tymnet>, Osman Guven
	<osman@X930.Tymnet>, Joe Smith <jms@X930.Tymnet> 
Resent-cc: Craig Fletcher <fletcherc@X930.Tymnet>, DenCoff 

     TO:       SOUTH BAY CONSOLIDATION EMPLOYEES

     FROM:     GINA ZWAAGSTRA

     DATE:     AUGUST 11, 1987

     SUBJECT:  FURNITURE TAGGING
     =================================================================

     STARTING AUGUST 11, 1986 THERE WILL BE 4 TEAMS OF 2 PEOPLE COMING
     AROUND TO TAG EXISTING FURNITURE.  BEFORE EACH OF THE NEXT MOVES.

     PLEASE DO NOT REMOVE THE TAGS FROM THE FURNITURE AS THIS WILL
     CAUSE GREAT CONFUSION AND A SHORTAGE FOR THE MOVES.

     THANK YOU FOR YOUR PATIENCE AND COOPERATION!!!
From: Joe Smith <JMS@X930> 
Date: Sat, 15 Aug 87 10:40:04 PDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: Test of Hotline 

At 10:20am Saturday my beeper went off, the number it displayed was
800 854-6000.  No system number this time.  I called it, and was given
three of the "please hold on" recordings before it was answered.  I gave
my name, stated that I was responding to TYMCOM-X Support.  She was expecting
Osman, and "DEC System Support".  She also asked for my employee number,
meaning the 4-digit FSC payroll number, not the 6-digit ISG number.  They
had Osman on call until 5:30pm Monday instead of me.  It looks like we need
to have a more formal schedule, instead of just a sheet of paper on my wall.

I called Emile at the Fremont Data Center at 10:23am.  End of call.
				/Joe

From: JMS@X930.Tymnet 
Date: Mon, 17 Aug 87 11:29:00 PDT 
To: carl, dencoff 
Subject: "I sent a compaint to SUBMIT. If"... 

I sent a compaint to SUBMIT.  If you read between the lines, it is asking for
timestamping in the log file.  /Joe
From: FLETCHERC@X930.Tymnet 
Date: Mon, 17 Aug 87 11:20:02 PDT 
To: dencoff 
Subject: "I would like you to be backup"... 

I would like you to be backup to Osman to show movers what to load for
135 Nicholson at 9:00 a.m. Wednesday August 26th.  This involves computers,
terminals, tapes, and two desks.

	Craig
From: Dennis Coffey (Tymcom-X Systems) <DenCoff@X930> 
Date: Mon, 17 Aug 87 11:42:49 PDT 
To: FLETCHERC@X930.Tymnet 
Subject: Re: "I would like you to be backup"... 
In-reply-to: your message of Mon, 17 Aug 87 11:20:02 PDT

Craig,

  I'll be glad to back Osman up, for the movers.

-Dennis-
From: Carl A Baltrunas <Carl@X930.Tymnet> 
Date: Mon, 17 Aug 87 21:28:39 PDT 
To: Joe Smith <JMS@X930> 
Cc: Monitor Group <JMS>, Osman, FletcherC, DenCoff 
Subject: Re: Test of Hotline 
In-reply-to: your message of Sat, 15 Aug 87 10:40:04 PDT

re: formal schedule

Obviously, our switching around seems to be the culprit, however... our
switching around didn't affect your being on-call this week.  The order of
record is "carl-osman-joe" and carl/osman swapped so they should have had
Joe on call this past week.

I believe that Craig mentioned that he thought Osman was on-call, and it
seems that is what he told dispatch?  Only guessing of course.  In any case
it shouldn't matter to dispatch, who is on-call as long as they page the
group pager number.  I am against having to notify dispatch if we change
the order amongst ourselves.... we notify Craig, and if dispatch cannot get
someone on the beeper, they will call Craig anyway.


We should bring it up as a discussion item in the meeting wednesday.

/Carl
Reply-to: SUBMIT 
From: X930 Job Processor 
Sender: PERPOPER@X930.Tymnet 
Date: Wed, 19 Aug 87 22:50:40 UT 
To: DENCOFF 
Subject: Req #11404 DSK:(DENCOFF)TST.CTL Done-End 

; Processed:  Req #11404 DSK:(DENCOFF)TST.LOG=DSK:(DENCOFF)TST.CTL
; Scheduled:  19-Aug-87 15:49:20
; Actual run: 19-Aug-87 15:49:46
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 5  TRUs 0
; Flags: 
; Status:  Done-End  at  19-Aug-87 15:50:37
;
; Output recorded in file DSK:(DENCOFF)TST.LOG.

Reply-to: SUBMIT 
From: X930 Job Processor 
Sender: PERPOPER@X930.Tymnet 
Date: Wed, 19 Aug 87 23:00:33 UT 
To: DENCOFF 
Subject: Req #11405 DSK:(DENCOFF)TST.CTL Abort-Zap (5) 

; Processed:  Req #11405 DSK:(DENCOFF)TST.LOG=DSK:(DENCOFF)TST.CTL
; Scheduled:  19-Aug-87 15:52:24
; Actual run: 19-Aug-87 15:52:27
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Abort-Zap (5)  at  19-Aug-87 16:00:27
;
; Output recorded in file DSK:(DENCOFF)TST.LOG.

Reply-to: SUBMIT 
From: X930 Job Processor 
Sender: PERPOPER@X930.Tymnet 
Date: Wed, 19 Aug 87 23:04:17 UT 
To: DENCOFF 
Subject: Req #11406 DSK:(DENCOFF)TST.CTL Abort-Time (5) 

; Processed:  Req #11406 DSK:(DENCOFF)TST.LOG=DSK:(DENCOFF)TST.CTL
; Scheduled:  19-Aug-87 15:58:46
; Actual run: 19-Aug-87 16:00:34
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 3  TRUs 0
; Flags: 
; Status:  Abort-Time (5)  at  19-Aug-87 16:04:14
;
; Output recorded in file DSK:(DENCOFF)TST.LOG.

From: Joe Smith <JMS@X930> 
Date: Thu, 20 Aug 87 11:19:51 PDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: Status of tape drives. 

Condition as of Wednesday morning:
Kennedy on AA would consistantly lose vacuum near end of reel.
Kennedy on BB hub release not working - no tapes could be mounted.
TU45 on DD would go off end or reel on save - EOT sensor has not been adjusted.

Condition as of Wednesday night:
Found how to adjust hub on Kennedy, can now mount tapes on BB.
Adjusted hub on AA slightly - now it does not lose vacuum.
DD's TU45 still waiting for someone who knows how to adjust it.
CC's TU45 moved into other room and connected to DD, ALL FILE save in progress.
			/Joe
Received: from D25.Tymnet by X930.Tymnet; Thu, 20 Aug 87 17:15:31 PDT
Return-path: <Postmaster@D25.Tymnet> 
From: Postmaster@D25.Tymnet 
Date: Thu, 20 Aug 87 17:15:07 PDT 
To: <DenCoff@X930> 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: NETALERT
Last logout: 14 Aug 87


----------
RCPT To: <netalert@c25.tymnet> 
Received: from X930.Tymnet by D25.Tymnet; Tue, 21 Jul 87 18:31:20 PDT
Return-path: <DenCoff@X930> 
From: Dennis Coffey (Tymcom-X Systems) <DenCoff@X930> 
Date: Tue, 21 Jul 87 18:15:20 PDT 
To: netalert@c25.tymnet 
Subject: New, more reliable way to run ALERT. 



                                  MEMORANDUM


                                                              TYMCOM-X SYSTEMS

DATE:  21-Jul-87

  TO:  Jeff Liu

FROM:  Dennis Coffey  (Tymcom-X Systems)

SUBJ:  A new, more reliable way to run the ALERT program.

------------------------------------------------------------------------------

Jeff,

  The following method should work for you.  It will automatically restart
your ALERT program at system startup, and every hour, if ALERT is not running.
If your ALERT program is running at the time SUBMIT tries to run it, a new
execution of your ALERT program will not be started.  (This is done with the
default setting of the UNIQUE option of the Job Processor system).  

  We did not offer you this option before, because we were initially concerned
that the Job Processor system could run out of jobs.  Now that we have some
experience with it, we know that this is not an immediate problem.

  The plan is:

1.)  Notify me, and I will give you file (NETALERT)AALERT.CTL, on host 25.

2.)  Run SUBMIT:
	a.) delete jobs ALERT and ALERTT;
	b.) enter a new job AALERT, by using the following commands to INSERT:
		DATE EVERY 1 HOUR REFERENCE 00:00
		INSERT AALERT.CTL
		TIMELIMIT 10
		MAIL ERROR
	c.) QUIT out of SUBMIT.

3.)  You can now eliminate file (NETALERT:25)ALERTT.CTL.

4.)  TELECOPY file AALERT.CTL to (NETALERT) on the other hosts.

5.)  Do steps "2." and "3." on the other hosts, with the following change to
the DATE line:
	a.) one of the other hosts:
		DATE EVERY 1 HOUR REFERENCE 00:20
	b.) the lasst host:
		DATE EVERY 1 HOUR REFERENCE 00:40



  The file AALERT.CTL contains the following commands to the Job Processor
system:
	.submit
	*insert alert.shr
	*timelimit 0
	*mail error
	*restart start
	*detach
	*q


  The Job Processor job, AALERT, runs SUBMIT to insert a job to run the ALERT
program, to start just one execution, immediately.  If ALERT is already
running, the UNIQUE option in the job ALERT prevents the Job Processor system
from starting ALERT again.  If ALERT starts and finds ALERT running from
another host it will quit and log off this host.

  If AALERT dooesn't successfully complete the SUBMIT job to enter ALERT,
within 10 minutes, AALERT will go away.  (ALERTT should never take more than 4
minutes to complete, so 10 minutes is plenty of time.)  This time limit will
open up a job slot in the Job Processor system, a job slot which would
otherwise be tied up with the hung-up AALERT job.  This will also free up the
JOB name (NETALERT)ALERTT, so it can be re-run at the next hour's execution
time.

  If you have any questions, please call.


-Dennis-
  
 { /Ó